/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, leases } from '@prisma/client'
import type {
    UseMutationOptions,
    UseQueryOptions,
    UseInfiniteQueryOptions,
    InfiniteData
} from '@tanstack/react-query'
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react'
import {
    useModelQuery,
    useInfiniteModelQuery,
    useModelMutation
} from '@zenstackhq/tanstack-query/runtime-v5/react'
import type {
    PickEnumerable,
    CheckSelect,
    QueryError,
    ExtraQueryOptions,
    ExtraMutationOptions
} from '@zenstackhq/tanstack-query/runtime-v5'
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta'
type DefaultError = QueryError
import {
    useSuspenseModelQuery,
    useSuspenseInfiniteModelQuery
} from '@zenstackhq/tanstack-query/runtime-v5/react'
import type {
    UseSuspenseQueryOptions,
    UseSuspenseInfiniteQueryOptions
} from '@tanstack/react-query'

export function useCreateleases(
    options?: Omit<
        UseMutationOptions<
            leases | undefined,
            DefaultError,
            Prisma.leasesCreateArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesCreateArgs,
        DefaultError,
        leases,
        true
    >(
        'leases',
        'POST',
        `${endpoint}/leases/create`,
        metadata,
        options,
        fetch,
        true
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesCreateArgs>,
            options?: Omit<
                UseMutationOptions<
                    | CheckSelect<
                          T,
                          leases,
                          Prisma.leasesGetPayload<T>
                      >
                    | undefined,
                    DefaultError,
                    Prisma.SelectSubset<T, Prisma.leasesCreateArgs>
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as
                | CheckSelect<T, leases, Prisma.leasesGetPayload<T>>
                | undefined
        }
    }
    return mutation
}

export function useCreateManyleases(
    options?: Omit<
        UseMutationOptions<
            Prisma.BatchPayload,
            DefaultError,
            Prisma.leasesCreateManyArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesCreateManyArgs,
        DefaultError,
        Prisma.BatchPayload,
        false
    >(
        'leases',
        'POST',
        `${endpoint}/leases/createMany`,
        metadata,
        options,
        fetch,
        false
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesCreateManyArgs>,
            options?: Omit<
                UseMutationOptions<
                    Prisma.BatchPayload,
                    DefaultError,
                    Prisma.SelectSubset<
                        T,
                        Prisma.leasesCreateManyArgs
                    >
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload
        }
    }
    return mutation
}

export function useFindManyleases<
    TArgs extends Prisma.leasesFindManyArgs,
    TQueryFnData = Array<
        Prisma.leasesGetPayload<TArgs> & { $optimistic?: boolean }
    >,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindManyArgs>,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findMany`,
        args,
        options,
        fetch
    )
}

export function useInfiniteFindManyleases<
    TArgs extends Prisma.leasesFindManyArgs,
    TQueryFnData = Array<Prisma.leasesGetPayload<TArgs>>,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindManyArgs>,
    options?: Omit<
        UseInfiniteQueryOptions<
            TQueryFnData,
            TError,
            InfiniteData<TData>
        >,
        'queryKey' | 'initialPageParam'
    >
) {
    options = options ?? { getNextPageParam: () => null }
    const { endpoint, fetch } = getHooksContext()
    return useInfiniteModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findMany`,
        args,
        options,
        fetch
    )
}

export function useSuspenseFindManyleases<
    TArgs extends Prisma.leasesFindManyArgs,
    TQueryFnData = Array<
        Prisma.leasesGetPayload<TArgs> & { $optimistic?: boolean }
    >,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindManyArgs>,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findMany`,
        args,
        options,
        fetch
    )
}

export function useSuspenseInfiniteFindManyleases<
    TArgs extends Prisma.leasesFindManyArgs,
    TQueryFnData = Array<Prisma.leasesGetPayload<TArgs>>,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindManyArgs>,
    options?: Omit<
        UseSuspenseInfiniteQueryOptions<
            TQueryFnData,
            TError,
            InfiniteData<TData>
        >,
        'queryKey' | 'initialPageParam'
    >
) {
    options = options ?? { getNextPageParam: () => null }
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findMany`,
        args,
        options,
        fetch
    )
}

export function useFindUniqueleases<
    TArgs extends Prisma.leasesFindUniqueArgs,
    TQueryFnData = Prisma.leasesGetPayload<TArgs> & {
        $optimistic?: boolean
    },
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<TArgs, Prisma.leasesFindUniqueArgs>,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findUnique`,
        args,
        options,
        fetch
    )
}

export function useSuspenseFindUniqueleases<
    TArgs extends Prisma.leasesFindUniqueArgs,
    TQueryFnData = Prisma.leasesGetPayload<TArgs> & {
        $optimistic?: boolean
    },
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<TArgs, Prisma.leasesFindUniqueArgs>,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findUnique`,
        args,
        options,
        fetch
    )
}

export function useFindFirstleases<
    TArgs extends Prisma.leasesFindFirstArgs,
    TQueryFnData = Prisma.leasesGetPayload<TArgs> & {
        $optimistic?: boolean
    },
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindFirstArgs>,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findFirst`,
        args,
        options,
        fetch
    )
}

export function useSuspenseFindFirstleases<
    TArgs extends Prisma.leasesFindFirstArgs,
    TQueryFnData = Prisma.leasesGetPayload<TArgs> & {
        $optimistic?: boolean
    },
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesFindFirstArgs>,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/findFirst`,
        args,
        options,
        fetch
    )
}

export function useUpdateleases(
    options?: Omit<
        UseMutationOptions<
            leases | undefined,
            DefaultError,
            Prisma.leasesUpdateArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesUpdateArgs,
        DefaultError,
        leases,
        true
    >(
        'leases',
        'PUT',
        `${endpoint}/leases/update`,
        metadata,
        options,
        fetch,
        true
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesUpdateArgs>,
            options?: Omit<
                UseMutationOptions<
                    | CheckSelect<
                          T,
                          leases,
                          Prisma.leasesGetPayload<T>
                      >
                    | undefined,
                    DefaultError,
                    Prisma.SelectSubset<T, Prisma.leasesUpdateArgs>
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as
                | CheckSelect<T, leases, Prisma.leasesGetPayload<T>>
                | undefined
        }
    }
    return mutation
}

export function useUpdateManyleases(
    options?: Omit<
        UseMutationOptions<
            Prisma.BatchPayload,
            DefaultError,
            Prisma.leasesUpdateManyArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesUpdateManyArgs,
        DefaultError,
        Prisma.BatchPayload,
        false
    >(
        'leases',
        'PUT',
        `${endpoint}/leases/updateMany`,
        metadata,
        options,
        fetch,
        false
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesUpdateManyArgs>,
            options?: Omit<
                UseMutationOptions<
                    Prisma.BatchPayload,
                    DefaultError,
                    Prisma.SelectSubset<
                        T,
                        Prisma.leasesUpdateManyArgs
                    >
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload
        }
    }
    return mutation
}

export function useUpsertleases(
    options?: Omit<
        UseMutationOptions<
            leases | undefined,
            DefaultError,
            Prisma.leasesUpsertArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesUpsertArgs,
        DefaultError,
        leases,
        true
    >(
        'leases',
        'POST',
        `${endpoint}/leases/upsert`,
        metadata,
        options,
        fetch,
        true
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesUpsertArgs>,
            options?: Omit<
                UseMutationOptions<
                    | CheckSelect<
                          T,
                          leases,
                          Prisma.leasesGetPayload<T>
                      >
                    | undefined,
                    DefaultError,
                    Prisma.SelectSubset<T, Prisma.leasesUpsertArgs>
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as
                | CheckSelect<T, leases, Prisma.leasesGetPayload<T>>
                | undefined
        }
    }
    return mutation
}

export function useDeleteleases(
    options?: Omit<
        UseMutationOptions<
            leases | undefined,
            DefaultError,
            Prisma.leasesDeleteArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesDeleteArgs,
        DefaultError,
        leases,
        true
    >(
        'leases',
        'DELETE',
        `${endpoint}/leases/delete`,
        metadata,
        options,
        fetch,
        true
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesDeleteArgs>,
            options?: Omit<
                UseMutationOptions<
                    | CheckSelect<
                          T,
                          leases,
                          Prisma.leasesGetPayload<T>
                      >
                    | undefined,
                    DefaultError,
                    Prisma.SelectSubset<T, Prisma.leasesDeleteArgs>
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as
                | CheckSelect<T, leases, Prisma.leasesGetPayload<T>>
                | undefined
        }
    }
    return mutation
}

export function useDeleteManyleases(
    options?: Omit<
        UseMutationOptions<
            Prisma.BatchPayload,
            DefaultError,
            Prisma.leasesDeleteManyArgs
        > &
            ExtraMutationOptions,
        'mutationFn'
    >
) {
    const { endpoint, fetch } = getHooksContext()
    const _mutation = useModelMutation<
        Prisma.leasesDeleteManyArgs,
        DefaultError,
        Prisma.BatchPayload,
        false
    >(
        'leases',
        'DELETE',
        `${endpoint}/leases/deleteMany`,
        metadata,
        options,
        fetch,
        false
    )
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.leasesDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.leasesDeleteManyArgs>,
            options?: Omit<
                UseMutationOptions<
                    Prisma.BatchPayload,
                    DefaultError,
                    Prisma.SelectSubset<
                        T,
                        Prisma.leasesDeleteManyArgs
                    >
                > &
                    ExtraMutationOptions,
                'mutationFn'
            >
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload
        }
    }
    return mutation
}

export function useAggregateLeases<
    TArgs extends Prisma.LeasesAggregateArgs,
    TQueryFnData = Prisma.GetLeasesAggregateType<TArgs>,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<TArgs, Prisma.LeasesAggregateArgs>,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'Leases',
        `${endpoint}/leases/aggregate`,
        args,
        options,
        fetch
    )
}

export function useSuspenseAggregateLeases<
    TArgs extends Prisma.LeasesAggregateArgs,
    TQueryFnData = Prisma.GetLeasesAggregateType<TArgs>,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<TArgs, Prisma.LeasesAggregateArgs>,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'Leases',
        `${endpoint}/leases/aggregate`,
        args,
        options,
        fetch
    )
}

export function useGroupByleases<
    TArgs extends Prisma.leasesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
        Prisma.Extends<'skip', Prisma.Keys<TArgs>>,
        Prisma.Extends<'take', Prisma.Keys<TArgs>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
        ? { orderBy: Prisma.leasesGroupByArgs['orderBy'] }
        : { orderBy?: Prisma.leasesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
        Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends TArgs['by'] extends never[]
        ? Prisma.True
        : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
        ? `Error: "by" must not be empty.`
        : HavingValid extends Prisma.False
          ? {
                [P in HavingFields]: P extends ByFields
                    ? never
                    : P extends string
                      ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                      : [
                            Error,
                            'Field ',
                            P,
                            ` in "having" needs to be provided in "by"`
                        ]
            }[HavingFields]
          : 'take' extends Prisma.Keys<TArgs>
            ? 'orderBy' extends Prisma.Keys<TArgs>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                      }[OrderFields]
                : 'Error: If you provide "take", you also need to provide "orderBy"'
            : 'skip' extends Prisma.Keys<TArgs>
              ? 'orderBy' extends Prisma.Keys<TArgs>
                  ? ByValid extends Prisma.True
                      ? {}
                      : {
                            [P in OrderFields]: P extends ByFields
                                ? never
                                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                        }[OrderFields]
                  : 'Error: If you provide "skip", you also need to provide "orderBy"'
              : ByValid extends Prisma.True
                ? {}
                : {
                      [P in OrderFields]: P extends ByFields
                          ? never
                          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields],
    TQueryFnData = {} extends InputErrors
        ? Array<
              PickEnumerable<
                  Prisma.LeasesGroupByOutputType,
                  TArgs['by']
              > & {
                  [P in keyof TArgs &
                      keyof Prisma.LeasesGroupByOutputType]: P extends '_count'
                      ? TArgs[P] extends boolean
                          ? number
                          : Prisma.GetScalarType<
                                TArgs[P],
                                Prisma.LeasesGroupByOutputType[P]
                            >
                      : Prisma.GetScalarType<
                            TArgs[P],
                            Prisma.LeasesGroupByOutputType[P]
                        >
              }
          >
        : InputErrors,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<
        TArgs,
        Prisma.SubsetIntersection<
            TArgs,
            Prisma.leasesGroupByArgs,
            OrderByArg
        > &
            InputErrors
    >,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/groupBy`,
        args,
        options,
        fetch
    )
}

export function useSuspenseGroupByleases<
    TArgs extends Prisma.leasesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
        Prisma.Extends<'skip', Prisma.Keys<TArgs>>,
        Prisma.Extends<'take', Prisma.Keys<TArgs>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
        ? { orderBy: Prisma.leasesGroupByArgs['orderBy'] }
        : { orderBy?: Prisma.leasesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
        Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends TArgs['by'] extends never[]
        ? Prisma.True
        : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
        ? `Error: "by" must not be empty.`
        : HavingValid extends Prisma.False
          ? {
                [P in HavingFields]: P extends ByFields
                    ? never
                    : P extends string
                      ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                      : [
                            Error,
                            'Field ',
                            P,
                            ` in "having" needs to be provided in "by"`
                        ]
            }[HavingFields]
          : 'take' extends Prisma.Keys<TArgs>
            ? 'orderBy' extends Prisma.Keys<TArgs>
                ? ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                      }[OrderFields]
                : 'Error: If you provide "take", you also need to provide "orderBy"'
            : 'skip' extends Prisma.Keys<TArgs>
              ? 'orderBy' extends Prisma.Keys<TArgs>
                  ? ByValid extends Prisma.True
                      ? {}
                      : {
                            [P in OrderFields]: P extends ByFields
                                ? never
                                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                        }[OrderFields]
                  : 'Error: If you provide "skip", you also need to provide "orderBy"'
              : ByValid extends Prisma.True
                ? {}
                : {
                      [P in OrderFields]: P extends ByFields
                          ? never
                          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields],
    TQueryFnData = {} extends InputErrors
        ? Array<
              PickEnumerable<
                  Prisma.LeasesGroupByOutputType,
                  TArgs['by']
              > & {
                  [P in keyof TArgs &
                      keyof Prisma.LeasesGroupByOutputType]: P extends '_count'
                      ? TArgs[P] extends boolean
                          ? number
                          : Prisma.GetScalarType<
                                TArgs[P],
                                Prisma.LeasesGroupByOutputType[P]
                            >
                      : Prisma.GetScalarType<
                            TArgs[P],
                            Prisma.LeasesGroupByOutputType[P]
                        >
              }
          >
        : InputErrors,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args: Prisma.SelectSubset<
        TArgs,
        Prisma.SubsetIntersection<
            TArgs,
            Prisma.leasesGroupByArgs,
            OrderByArg
        > &
            InputErrors
    >,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/groupBy`,
        args,
        options,
        fetch
    )
}

export function useCountleases<
    TArgs extends Prisma.leasesCountArgs,
    TQueryFnData = TArgs extends { select: any }
        ? TArgs['select'] extends true
            ? number
            : Prisma.GetScalarType<
                  TArgs['select'],
                  Prisma.LeasesCountAggregateOutputType
              >
        : number,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesCountArgs>,
    options?: Omit<
        UseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/count`,
        args,
        options,
        fetch
    )
}

export function useSuspenseCountleases<
    TArgs extends Prisma.leasesCountArgs,
    TQueryFnData = TArgs extends { select: any }
        ? TArgs['select'] extends true
            ? number
            : Prisma.GetScalarType<
                  TArgs['select'],
                  Prisma.LeasesCountAggregateOutputType
              >
        : number,
    TData = TQueryFnData,
    TError = DefaultError
>(
    args?: Prisma.SelectSubset<TArgs, Prisma.leasesCountArgs>,
    options?: Omit<
        UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useSuspenseModelQuery<TQueryFnData, TData, TError>(
        'leases',
        `${endpoint}/leases/count`,
        args,
        options,
        fetch
    )
}
import type { LeaseType } from '@prisma/client'

export function useCheckleases<TError = DefaultError>(
    args: {
        operation: PolicyCrudKind
        where?: {
            user_id?: string
            tenant_id?: string
            property_id?: string
            lease_type?: LeaseType
            payment_day?: number
            documents?: string
            lease_status?: string
        }
    },
    options?: Omit<
        UseQueryOptions<boolean, TError, boolean>,
        'queryKey'
    > &
        ExtraQueryOptions
) {
    const { endpoint, fetch } = getHooksContext()
    return useModelQuery<boolean, boolean, TError>(
        'leases',
        `${endpoint}/leases/check`,
        args,
        options,
        fetch
    )
}
